[package]
name = "sergeant"
version = "0.11.0"
edition = "2021"
description = "Sergeant is a terminal based Twitch chat widget and bot in one. It will display the Twitch chat from your channel in terminal while also allowing you to add chat bot commands."
license = "MIT OR Apache-2.0"
repository = "https://github.com/s9tpepper/sergeant"
keywords = ["twitch", "chat", "bot"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
  "commands/intros",
  "commands/spotify"
]


[dependencies]
anathema = { git = "https://github.com/togglebyte/anathema.git", branch = "dev"  }
anyhow = "1.0.95"
base64 = "0.22.1"
clap = { version = "4.6.0", features = ["derive", "env", "cargo"] }
color-eyre = "0.6.3"
color-name = "1.1.0"
colored = "3.1.0"
crossterm = "0.29.0"
descape = "3.0.0"
directories = "6.0.0"
dotenv = { version = "0.15.0", features = ["cli", "clap"] }
features = "0.10.0"
full = "0.3.0"
# hex-rgb = "0.1.1"
image = "0.25.1"
log = "0.4.25"
ratatui = "0.30.0"
serde = { version = "1.0.228", features = ["alloc", "derive", "serde_derive"] }
serde_json = "1.0.149"
simplelog = "0.12.2"
thiserror = "2.0.16"
time = "0.3.47"
tungstenite = { version = "0.28.0", features = ["native-tls"] }
ureq = { version = "2.12.1", features = ["json"] }
url = "2.5.1"
uuid = "1.8.0"
